import { Router, type IRouter } from "express";
import { requireFeature } from "../../middleware/feature";
import { onlyForPaths } from "../../middleware/pathGate";
import patientsRouter from "./patients";
import appointmentsRouter from "./appointments";
import visitsRouter from "./visits";
import medicalInvoicesRouter from "./invoices";
import reportsRouter from "./reports";
import materialsRouter from "./materials";
import prescriptionsRouter from "./prescriptions";
import medicineMasterRouter from "./medicine-master";
import doctorTemplatesRouter from "./doctor-templates";
import diagnosesMasterRouter from "./diagnoses-master";
import alertsRouter from "./alerts";
import doctorAvailabilityRouter from "./doctor-availability";
import aiSummaryRouter from "./ai-summary";
import patientDocumentsRouter from "./patient-documents";
import prescriptionOcrRouter from "./prescription-ocr";

const router: IRouter = Router();

router.use(onlyForPaths("/patients", requireFeature("medical_patients")));
router.use(patientsRouter);
router.use(onlyForPaths("/appointments", requireFeature("medical_appointments")));
router.use(appointmentsRouter);
router.use(onlyForPaths("/visits", requireFeature("medical_visits")));
router.use(visitsRouter);
router.use(onlyForPaths("/medical-invoices", requireFeature("medical_invoices")));
router.use(medicalInvoicesRouter);
router.use(onlyForPaths("/medical-reports", requireFeature("medical_reports")));
router.use(reportsRouter);
router.use(onlyForPaths("/medical-materials", requireFeature("medical_materials")));
router.use(materialsRouter);
router.use(onlyForPaths(["/prescriptions", "/prescriptions-stats"], requireFeature("medical_prescriptions")));
router.use(prescriptionsRouter);
router.use(onlyForPaths("/medicine-master", requireFeature("medical_medicine_master")));
router.use(medicineMasterRouter);
router.use(onlyForPaths("/doctor-prescription-templates", requireFeature("medical_rx_templates")));
router.use(doctorTemplatesRouter);
router.use(onlyForPaths(["/diagnoses-master", "/medical-features-master"], requireFeature("medical_visits")));
router.use(diagnosesMasterRouter);
router.use(onlyForPaths("/medical-alerts", requireFeature("medical_patients")));
router.use(alertsRouter);
router.use(onlyForPaths("/doctor-availability", requireFeature("medical_doctor_availability")));
router.use(doctorAvailabilityRouter);
router.use(onlyForPaths("/patients", requireFeature("medical_ai_summary")));
router.use(aiSummaryRouter);
router.use(onlyForPaths("/patients", requireFeature("medical_patient_documents")));
router.use(patientDocumentsRouter);
router.use(onlyForPaths("/prescriptions", requireFeature("medical_prescription_ocr")));
router.use(prescriptionOcrRouter);

export default router;
