/** Egyptian clinic market — default catalogs seeded into each tenant DB. */

export type CatalogItem = { en: string; ar: string; value?: string; meta?: Record<string, unknown> };

export const EGYPT_PROCEDURES: { name: string; nameAr: string; category: string; price: number }[] = [
  { name: "General consultation", nameAr: "كشف عيادات عام", category: "consultation", price: 300 },
  { name: "Follow-up visit", nameAr: "متابعة", category: "consultation", price: 200 },
  { name: "Emergency consultation", nameAr: "كشف طوارئ", category: "consultation", price: 500 },
  { name: "ECG", nameAr: "رسم قلب", category: "diagnostics", price: 150 },
  { name: "Blood sugar test", nameAr: "تحليل سكر", category: "lab", price: 80 },
  { name: "CBC", nameAr: "صورة دم كاملة", category: "lab", price: 120 },
  { name: "HbA1c", nameAr: "سكر تراكمي", category: "lab", price: 200 },
  { name: "Lipid profile", nameAr: "دهون ثلاثية وكوليسترول", category: "lab", price: 250 },
  { name: "Urine analysis", nameAr: "تحليل بول", category: "lab", price: 60 },
  { name: "X-ray (single view)", nameAr: "أشعة سينية", category: "imaging", price: 200 },
  { name: "Ultrasound abdomen", nameAr: "سونار بطن", category: "imaging", price: 350 },
  { name: "Wound dressing", nameAr: "تضميد جروح", category: "procedure", price: 100 },
  { name: "Injection IM", nameAr: "حقنة عضل", category: "procedure", price: 50 },
  { name: "IV fluid session", nameAr: "محلول وريدي", category: "procedure", price: 150 },
  { name: "Nebulizer session", nameAr: "بخاخ / نيبولايزر", category: "procedure", price: 120 },
  { name: "Physio session (30 min)", nameAr: "جلسة علاج طبيعي", category: "physiotherapy", price: 350 },
  { name: "Nutrition consultation", nameAr: "استشارة تغذية علاجية", category: "nutrition", price: 400 },
  { name: "Dental extraction", nameAr: "خلع سن", category: "dental", price: 400 },
  { name: "Dental filling", nameAr: "حشو سن", category: "dental", price: 350 },
  { name: "Scaling & polishing", nameAr: "تنظيف وتلميع أسنان", category: "dental", price: 500 },
];

export const EGYPT_MATERIALS: { name: string; nameAr: string; category: string; unit: string; unitPrice: number; sku: string }[] = [
  { name: "Disposable gloves (box)", nameAr: "قفازات طبية (علبة)", category: "consumable", unit: "box", unitPrice: 120, sku: "GLV-001" },
  { name: "Syringe 5ml", nameAr: "حقنة 5 مل", category: "consumable", unit: "pcs", unitPrice: 3, sku: "SYR-5" },
  { name: "Gauze pack", nameAr: "شاش طبي", category: "consumable", unit: "pack", unitPrice: 25, sku: "GAU-01" },
  { name: "Alcohol swabs", nameAr: "مسحات كحول", category: "consumable", unit: "box", unitPrice: 45, sku: "ALC-01" },
  { name: "Face mask (box)", nameAr: "كمامات (علبة)", category: "consumable", unit: "box", unitPrice: 80, sku: "MSK-01" },
  { name: "Cotton rolls", nameAr: "قطن طبي", category: "consumable", unit: "pack", unitPrice: 35, sku: "CTN-01" },
  { name: "Saline 500ml", nameAr: "محلول ملحي 500 مل", category: "medication", unit: "bottle", unitPrice: 15, sku: "SAL-500" },
  { name: "ECG electrodes", nameAr: "أقطاب تخطيط قلب", category: "equipment", unit: "pack", unitPrice: 90, sku: "ECG-E" },
];

export const EGYPT_PHYSIO_EXERCISES: { name: string; nameAr: string; category: string; bodyRegion: string; durationMinutes: number }[] = [
  { name: "Heel slides", nameAr: "انزلاق الكعب", category: "stretching", bodyRegion: "Knee", durationMinutes: 10 },
  { name: "Quad sets", nameAr: "تقوية الفخذ الأمامي", category: "strengthening", bodyRegion: "Knee", durationMinutes: 10 },
  { name: "Shoulder pendulum", nameAr: "بندول الكتف", category: "mobility", bodyRegion: "Shoulder", durationMinutes: 8 },
  { name: "Cat-cow stretch", nameAr: "تمرين القطة والبقرة", category: "stretching", bodyRegion: "Lumbar spine", durationMinutes: 5 },
  { name: "Bridging", nameAr: "جسر الحوض", category: "strengthening", bodyRegion: "Lumbar spine", durationMinutes: 10 },
  { name: "Cervical rotation", nameAr: "دوران الرقبة", category: "mobility", bodyRegion: "Cervical spine", durationMinutes: 5 },
  { name: "Ankle circles", nameAr: "دوران الكاحل", category: "mobility", bodyRegion: "Ankle", durationMinutes: 5 },
  { name: "TENS / electrotherapy", nameAr: "تنس / كهرباء علاجية", category: "electrotherapy", bodyRegion: "General", durationMinutes: 15 },
  { name: "Ultrasound therapy", nameAr: "علاج بالموجات فوق صوتية", category: "electrotherapy", bodyRegion: "General", durationMinutes: 10 },
  { name: "Hot pack", nameAr: "كمادات ساخنة", category: "manual", bodyRegion: "General", durationMinutes: 15 },
];

export const EGYPT_FOODS: { name: string; nameAr: string; category: string; servingSize: string; caloriesKcal: number; proteinG: number; carbsG: number; fatG: number }[] = [
  { name: "Ful medames", nameAr: "فول مدمس", category: "egyptian_dishes", servingSize: "1 cup", caloriesKcal: 180, proteinG: 10, carbsG: 28, fatG: 4 },
  { name: "Taameya (falafel)", nameAr: "طعمية", category: "egyptian_dishes", servingSize: "3 pieces", caloriesKcal: 220, proteinG: 8, carbsG: 24, fatG: 12 },
  { name: "Koshari", nameAr: "كشري", category: "egyptian_dishes", servingSize: "1 plate", caloriesKcal: 450, proteinG: 14, carbsG: 75, fatG: 10 },
  { name: "Grilled chicken breast", nameAr: "صدر دجاج مشوي", category: "proteins", servingSize: "150g", caloriesKcal: 248, proteinG: 46, carbsG: 0, fatG: 5 },
  { name: "Brown rice", nameAr: "أرز بني", category: "grains", servingSize: "1 cup cooked", caloriesKcal: 216, proteinG: 5, carbsG: 45, fatG: 2 },
  { name: "White rice", nameAr: "أرز أبيض", category: "grains", servingSize: "1 cup cooked", caloriesKcal: 205, proteinG: 4, carbsG: 45, fatG: 0 },
  { name: "Baladi bread", nameAr: "عيش بلدي", category: "grains", servingSize: "1 piece", caloriesKcal: 150, proteinG: 5, carbsG: 30, fatG: 1 },
  { name: "Lentil soup", nameAr: "شوربة عدس", category: "egyptian_dishes", servingSize: "1 bowl", caloriesKcal: 160, proteinG: 9, carbsG: 22, fatG: 4 },
  { name: "Cucumber tomato salad", nameAr: "سلطة خيار وطماطم", category: "vegetables", servingSize: "1 cup", caloriesKcal: 45, proteinG: 2, carbsG: 8, fatG: 1 },
  { name: "Molokhia", nameAr: "ملوخية", category: "egyptian_dishes", servingSize: "1 cup", caloriesKcal: 95, proteinG: 6, carbsG: 8, fatG: 5 },
  { name: "Greek yogurt", nameAr: "زبادي يوناني", category: "dairy", servingSize: "170g", caloriesKcal: 100, proteinG: 17, carbsG: 6, fatG: 0 },
  { name: "Dates", nameAr: "بلح", category: "fruits", servingSize: "3 pieces", caloriesKcal: 66, proteinG: 0, carbsG: 18, fatG: 0 },
];

export const EGYPT_DIAGNOSES: CatalogItem[] = [
  { en: "Hypertension", ar: "ارتفاع ضغط الدم", value: "hypertension" },
  { en: "Type 2 diabetes", ar: "سكر نوع 2", value: "diabetes_t2" },
  { en: "Type 1 diabetes", ar: "سكر نوع 1", value: "diabetes_t1" },
  { en: "Upper respiratory infection", ar: "التهاب تنفسي علوي", value: "uri" },
  { en: "Bronchitis", ar: "التهاب الشعب الهوائية", value: "bronchitis" },
  { en: "Pneumonia", ar: "التهاب رئوي", value: "pneumonia" },
  { en: "Gastritis", ar: "التهاب المعدة", value: "gastritis" },
  { en: "GERD", ar: "ارتجاع مريئي", value: "gerd" },
  { en: "Hepatitis", ar: "التهاب الكبد", value: "hepatitis" },
  { en: "Low back pain", ar: "آلام أسفل الظهر", value: "lbp" },
  { en: "Cervical spondylosis", ar: "التهاب الفقرات العنقية", value: "cervical_sp" },
  { en: "Osteoarthritis knee", ar: "خشونة الركبة", value: "oa_knee" },
  { en: "Rheumatoid arthritis", ar: "التهاب مفاصل روماتويدي", value: "ra" },
  { en: "Vitamin D deficiency", ar: "نقص فيتامين د", value: "vitd_def" },
  { en: "Iron deficiency anemia", ar: "أنيميا نقص حديد", value: "ida" },
  { en: "Obesity", ar: "سمنة", value: "obesity" },
  { en: "Migraine", ar: "صداع نصفي", value: "migraine" },
  { en: "Tension headache", ar: "صداع توتري", value: "tension_ha" },
  { en: "Urinary tract infection", ar: "التهاب مسالك بولية", value: "uti" },
  { en: "Allergic rhinitis", ar: "حساسية الأنف", value: "allergic_rhinitis" },
  { en: "Eczema", ar: "إكزيما", value: "eczema" },
  { en: "Acne vulgaris", ar: "حب الشباب", value: "acne" },
  { en: "Anxiety disorder", ar: "اضطراب قلق", value: "anxiety" },
  { en: "Depression", ar: "اكتئاب", value: "depression" },
  { en: "Pregnancy follow-up", ar: "متابعة حمل", value: "pregnancy_fu" },
];

export const EGYPT_CHRONIC_CONDITIONS: CatalogItem[] = [
  { en: "Diabetes", ar: "السكري" },
  { en: "Hypertension", ar: "ضغط الدم" },
  { en: "Heart disease", ar: "أمراض القلب" },
  { en: "Asthma", ar: "الربو" },
  { en: "COPD", ar: "الانسداد الرئوي المزمن" },
  { en: "Thyroid disorder", ar: "اضطراب الغدة الدرقية" },
  { en: "Kidney disease", ar: "أمراض الكلى" },
  { en: "Liver disease", ar: "أمراض الكبد" },
  { en: "Obesity", ar: "السمنة" },
  { en: "Hyperlipidemia", ar: "ارتفاع الدهون" },
  { en: "Osteoporosis", ar: "هشاشة العظام" },
  { en: "Rheumatoid arthritis", ar: "التهاب مفاصل روماتويدي" },
  { en: "Epilepsy", ar: "الصرع" },
  { en: "Depression", ar: "الاكتئاب" },
];

export const EGYPT_ALLERGIES: CatalogItem[] = [
  { en: "Penicillin", ar: "بنسلين" },
  { en: "Aspirin", ar: "أسبرين" },
  { en: "Sulfa drugs", ar: "سلفا" },
  { en: "Ibuprofen", ar: "إيبوبروفين" },
  { en: "Latex", ar: "لاتكس" },
  { en: "Peanuts", ar: "فول سوداني" },
  { en: "Tree nuts", ar: "مكسرات" },
  { en: "Seafood", ar: "مأكولات بحرية" },
  { en: "Eggs", ar: "بيض" },
  { en: "Milk / dairy", ar: "لبن / ألبان" },
  { en: "Wheat / gluten", ar: "قمح / جلوتين" },
  { en: "Dust mites", ar: "عث الغبار" },
  { en: "Pollen", ar: "حبوب اللقاح" },
  { en: "Insect stings", ar: "لسعات الحشرات" },
];

export const EGYPT_MEDICATIONS: CatalogItem[] = [
  { en: "Paracetamol 500mg", ar: "باراسيتامول 500 مج" },
  { en: "Ibuprofen 400mg", ar: "إيبوبروفين 400 مج" },
  { en: "Diclofenac 50mg", ar: "ديكلوفيناك 50 مج" },
  { en: "Amoxicillin 500mg", ar: "أموكسيسيلين 500 مج" },
  { en: "Azithromycin 500mg", ar: "أزيثروميسين 500 مج" },
  { en: "Ciprofloxacin 500mg", ar: "سيبروفلوكساسين 500 مج" },
  { en: "Metformin 500mg", ar: "ميتفورمين 500 مج" },
  { en: "Glibenclamide 5mg", ar: "جليبنكلاميد 5 مج" },
  { en: "Insulin NPH", ar: "أنسولين NPH" },
  { en: "Amlodipine 5mg", ar: "أملوديبين 5 مج" },
  { en: "Losartan 50mg", ar: "لوسارتان 50 مج" },
  { en: "Atenolol 50mg", ar: "أتينولول 50 مج" },
  { en: "Omeprazole 20mg", ar: "أوميبرازول 20 مج" },
  { en: "Ranitidine 150mg", ar: "رانيتيدين 150 مج" },
  { en: "Salbutamol inhaler", ar: "بخاخ سالبيوتامول" },
  { en: "Cetirizine 10mg", ar: "سيتريزين 10 مج" },
  { en: "Vitamin D 1000 IU", ar: "فيتامين د 1000 وحدة" },
  { en: "Iron supplement", ar: "مكمل حديد" },
  { en: "Calcium + Vitamin D", ar: "كالسيوم + فيتامين د" },
  { en: "ORS sachets", ar: "أكياس محلول معالجة الجفاف" },
];

export const EGYPT_INSURANCE_PROVIDERS: CatalogItem[] = [
  { en: "General Authority for Health Insurance", ar: "الهيئة العامة للتأمين الصحي", value: "general_authority" },
  { en: "AXA Egypt", ar: "أكسا مصر" },
  { en: "Allianz Egypt", ar: "أليانز مصر" },
  { en: "MetLife Alico", ar: "ميتلايف أليكو" },
  { en: "Bupa Egypt", ar: "بوبا مصر" },
  { en: "Corporate employer plan", ar: "تأمين جهة العمل" },
];

export const EGYPT_CITIES_BY_GOVERNORATE: Record<string, CatalogItem[]> = {
  Cairo: [
    { en: "Nasr City", ar: "مدينة نصر" }, { en: "Maadi", ar: "المعادي" },
    { en: "Heliopolis", ar: "مصر الجديدة" }, { en: "Downtown", ar: "وسط البلد" },
    { en: "Shubra", ar: "شبرا" }, { en: "New Cairo", ar: "القاهرة الجديدة" },
    { en: "Zamalek", ar: "الزمالك" }, { en: "Mokattam", ar: "المقطم" },
  ],
  Giza: [
    { en: "Dokki", ar: "الدقي" }, { en: "Mohandessin", ar: "المهندسين" },
    { en: "6th of October", ar: "6 أكتوبر" }, { en: "Haram", ar: "الهرم" },
    { en: "Faisal", ar: "فيصل" }, { en: "Sheikh Zayed", ar: "الشيخ زايد" },
  ],
  Alexandria: [
    { en: "Miami", ar: "ميامي" }, { en: "Smouha", ar: "سموحة" },
    { en: "Agami", ar: "العجمي" }, { en: "Mansheya", ar: "المنشية" },
    { en: "Stanley", ar: "ستانلي" }, { en: "Borg El Arab", ar: "برج العرب" },
  ],
  Dakahlia: [{ en: "Mansoura", ar: "المنصورة" }, { en: "Talkha", ar: "طلخا" }, { en: "Mit Ghamr", ar: "ميت غمر" }],
  "Red Sea": [{ en: "Hurghada", ar: "الغردقة" }, { en: "Safaga", ar: "سفاجا" }, { en: "Marsa Alam", ar: "مرسى علم" }],
  Beheira: [{ en: "Damanhour", ar: "دمنهور" }, { en: "Rashid", ar: "رشيد" }, { en: "Edku", ar: "إدكو" }],
  Fayoum: [{ en: "Fayoum City", ar: "مدينة الفيوم" }, { en: "Tamiya", ar: "طامية" }],
  Gharbia: [{ en: "Tanta", ar: "طنطا" }, { en: "Mahalla El Kubra", ar: "المحلة الكبرى" }, { en: "Zifta", ar: "زفتى" }],
  Ismailia: [{ en: "Ismailia City", ar: "مدينة الإسماعيلية" }, { en: "Fayed", ar: "فايد" }],
  Menofia: [{ en: "Shibin El Kom", ar: "شبين الكوم" }, { en: "Sadat City", ar: "مدينة السادات" }],
  Minya: [{ en: "Minya City", ar: "مدينة المنيا" }, { en: "Mallawi", ar: "ملوي" }],
  Qalyubia: [{ en: "Banha", ar: "بنها" }, { en: "Qalyub", ar: "قليوب" }, { en: "Shubra El Kheima", ar: "شبرا الخيمة" }],
  "New Valley": [{ en: "Kharga", ar: "الخارجة" }, { en: "Dakhla", ar: "الداخلة" }],
  Suez: [{ en: "Suez City", ar: "مدينة السويس" }, { en: "Arbaeen", ar: "الأربعين" }],
  Aswan: [{ en: "Aswan City", ar: "مدينة أسوان" }, { en: "Kom Ombo", ar: "كوم أمبو" }],
  Assiut: [{ en: "Assiut City", ar: "مدينة أسيوط" }, { en: "Dayrout", ar: "ديروط" }],
  "Beni Suef": [{ en: "Beni Suef City", ar: "مدينة بني سويف" }, { en: "Nasser", ar: "ناصر" }],
  "Port Said": [{ en: "Port Said City", ar: "مدينة بورسعيد" }, { en: "Port Fouad", ar: "بورفؤاد" }],
  Damietta: [{ en: "Damietta City", ar: "مدينة دمياط" }, { en: "New Damietta", ar: "دمياط الجديدة" }],
  Sharkia: [{ en: "Zagazig", ar: "الزقازيق" }, { en: "10th of Ramadan", ar: "العاشر من رمضان" }, { en: "Belbeis", ar: "بلبيس" }],
  "South Sinai": [{ en: "Sharm El Sheikh", ar: "شرم الشيخ" }, { en: "Dahab", ar: "دهب" }, { en: "Nuweiba", ar: "نويبع" }],
  "Kafr El Sheikh": [{ en: "Kafr El Sheikh City", ar: "مدينة كفر الشيخ" }, { en: "Desouk", ar: "دسوق" }],
  Matrouh: [{ en: "Marsa Matrouh", ar: "مرسى مطروح" }, { en: "El Alamein", ar: "العلمين" }],
  Luxor: [{ en: "Luxor City", ar: "مدينة الأقصر" }, { en: "Esna", ar: "إسنا" }],
  Qena: [{ en: "Qena City", ar: "مدينة قنا" }, { en: "Nag Hammadi", ar: "نجع حمادي" }],
  "North Sinai": [{ en: "Arish", ar: "العريش" }, { en: "Sheikh Zuweid", ar: "الشيخ زويد" }],
  Sohag: [{ en: "Sohag City", ar: "مدينة سوهاج" }, { en: "Akhmim", ar: "أخميم" }],
};

export const EGYPT_PHYSIO_MODALITIES: CatalogItem[] = [
  { en: "Ultrasound", ar: "موجات فوق صوتية" },
  { en: "TENS", ar: "تنس" },
  { en: "Hot pack", ar: "كمادات ساخنة" },
  { en: "Cold pack", ar: "كمادات باردة" },
  { en: "Manual therapy", ar: "علاج يدوي" },
  { en: "Dry needling", ar: "إبر جافة" },
];

export const PROCEDURE_CATEGORIES_EGYPT: CatalogItem[] = [
  { en: "Consultation", ar: "كشف", value: "consultation" },
  { en: "Lab", ar: "تحاليل", value: "lab" },
  { en: "Imaging", ar: "أشعة", value: "imaging" },
  { en: "Procedure", ar: "إجراء", value: "procedure" },
  { en: "Dental", ar: "أسنان", value: "dental" },
  { en: "Physiotherapy", ar: "علاج طبيعي", value: "physiotherapy" },
  { en: "Nutrition", ar: "تغذية", value: "nutrition" },
  { en: "Diagnostics", ar: "تشخيص", value: "diagnostics" },
];
